#include "codegen_internal.h"

static void emit_stack_and_closure_ops(void) {
    z80_add_label(&enc, "vm_halt");
    z80_ld_r_n(&enc, REG_H, 0);     // Return code success.
    z80_ld_r_n(&enc, REG_L, 15);    // Zeal Exit
    z80_rst(&enc, 0x08);            // Syscall

    z80_add_label(&enc, "op_pop");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_TABLE);
    z80_jr_cc_label(&enc, CC_NZ, "op_pop_done");
    z80_call_label(&enc, "queue_table_reclaim_candidate");
    z80_add_label(&enc, "op_pop_done");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_dup");
    z80_call_label(&enc, "vstack_pop");
    z80_push(&enc, RP_AF); z80_push(&enc, RP_HL);
    z80_call_label(&enc, "vstack_push");
    z80_pop(&enc, RP_HL); z80_pop(&enc, RP_AF);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_loadnil");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, 0);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_loadtrue");
    z80_ld_rp_nn(&enc, RP_HL, 1);
    z80_ld_r_n(&enc, REG_A, 1);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_loadfalse");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, 1);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_loadconst");
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_ld_r_r(&enc, REG_L, REG_A); z80_ld_r_n(&enc, REG_H, 0); z80_ld_r_r(&enc, REG_E, REG_L); z80_ld_r_r(&enc, REG_D, REG_H); z80_add_hl_rp(&enc, RP_HL); z80_add_hl_rp(&enc, RP_DE);
    z80_ld_de_mem_label(&enc, "cp_ptr"); z80_add_hl_rp(&enc, RP_DE);
    z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL); z80_ld_r_r(&enc, REG_E, REG_M); z80_inc_rp(&enc, RP_HL); z80_ld_r_r(&enc, REG_D, REG_M); z80_ex_de_hl(&enc);
    z80_call_label(&enc, "vstack_push"); z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_rot3");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "table_key_temp");
    z80_ld_rp_label(&enc, RP_HL, "table_key_type");
    z80_ld_hl_a(&enc);
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "table_entry_temp");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "table_val_temp");
    z80_ld_rp_label(&enc, RP_HL, "table_val_type");
    z80_ld_hl_a(&enc);
    z80_ld_hl_mem_label(&enc, "table_entry_temp");
    z80_ld_r_n(&enc, REG_A, TYPE_TABLE);
    z80_call_label(&enc, "vstack_push");
    z80_ld_hl_mem_label(&enc, "table_key_temp");
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_HL, "table_key_type");
    z80_ld_a_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_call_label(&enc, "vstack_push");
    z80_ld_hl_mem_label(&enc, "table_val_temp");
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_HL, "table_val_type");
    z80_ld_a_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_print");
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_ld_r_r(&enc, REG_B, REG_A);
    z80_add_label(&enc, "op_print_loop");
    z80_ld_r_r(&enc, REG_A, REG_B); z80_or_a(&enc); z80_jp_cc_label(&enc, CC_Z, "vm_loop");
    z80_push(&enc, RP_BC);
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_NUMBER);
    z80_jp_cc_label(&enc, CC_Z, "op_print_number");
    z80_call_label(&enc, "coerce_to_string");
    z80_call_label(&enc, "print_str");
    z80_jp_label(&enc, "op_print_next");
    z80_add_label(&enc, "op_print_number");
    z80_call_label(&enc, "print_num");
    z80_add_label(&enc, "op_print_next");
    z80_ld_rp_label(&enc, RP_HL, "str_newline"); z80_call_label(&enc, "print_str");
    z80_pop(&enc, RP_BC); z80_djnz_label(&enc, "op_print_loop");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_type");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_NIL); z80_jr_cc_label(&enc, CC_Z, "type_nil");
    z80_cp_a_n(&enc, TYPE_BOOL); z80_jr_cc_label(&enc, CC_Z, "type_boolean");
    z80_cp_a_n(&enc, TYPE_NUMBER); z80_jr_cc_label(&enc, CC_Z, "type_number");
    z80_cp_a_n(&enc, TYPE_STRING); z80_jr_cc_label(&enc, CC_Z, "type_string");
    z80_cp_a_n(&enc, TYPE_TABLE); z80_jr_cc_label(&enc, CC_Z, "type_table");
    z80_ld_rp_label(&enc, RP_HL, "str_type_function");
    z80_jr_label(&enc, "type_push");
    z80_add_label(&enc, "type_nil");
    z80_ld_rp_label(&enc, RP_HL, "str_type_nil");
    z80_jr_label(&enc, "type_push");
    z80_add_label(&enc, "type_boolean");
    z80_ld_rp_label(&enc, RP_HL, "str_type_boolean");
    z80_jr_label(&enc, "type_push");
    z80_add_label(&enc, "type_number");
    z80_ld_rp_label(&enc, RP_HL, "str_type_number");
    z80_jr_label(&enc, "type_push");
    z80_add_label(&enc, "type_string");
    z80_ld_rp_label(&enc, RP_HL, "str_type_string");
    z80_jr_label(&enc, "type_push");
    z80_add_label(&enc, "type_table");
    z80_ld_rp_label(&enc, RP_HL, "str_type_table");
    z80_add_label(&enc, "type_push");
    z80_ld_r_n(&enc, REG_A, TYPE_STRING);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_tonumber");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_NUMBER); z80_jr_cc_label(&enc, CC_Z, "tonumber_push");
    z80_cp_a_n(&enc, TYPE_STRING); z80_jr_cc_label(&enc, CC_Z, "tonumber_parse");
    z80_jr_label(&enc, "tonumber_nil");
    z80_add_label(&enc, "tonumber_parse");
    z80_call_label(&enc, "string_to_number");
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "tonumber_nil");
    z80_add_label(&enc, "tonumber_push");
    z80_ld_r_n(&enc, REG_A, TYPE_NUMBER);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");
    z80_add_label(&enc, "tonumber_nil");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_tostring");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_ld_r_n(&enc, REG_A, TYPE_STRING);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_input");
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "op_input_read");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_call_label(&enc, "print_str");
    z80_add_label(&enc, "op_input_read");
    z80_call_label(&enc, "read_line_string");
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_readfile");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_call_label(&enc, "read_file_string");
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_writefile");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_ld_mem_hl_label(&enc, "writefile_data_ptr");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_call_label(&enc, "write_file_string");
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_open");
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_cp_a_n(&enc, 2);
    z80_jr_cc_label(&enc, CC_Z, "op_open_with_flags");
    z80_ld_rp_label(&enc, RP_HL, "open_flags");
    z80_xor_a(&enc);
    z80_ld_hl_a(&enc);
    z80_jr_label(&enc, "op_open_pop_path");
    z80_add_label(&enc, "op_open_with_flags");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_NUMBER);
    z80_jr_cc_label(&enc, CC_Z, "op_open_store_flags");
    z80_xor_a(&enc);
    z80_ld_r_r(&enc, REG_L, REG_A);
    z80_add_label(&enc, "op_open_store_flags");
    z80_ld_rp_label(&enc, RP_HL, "open_flags");
    z80_ld_hl_a(&enc);
    z80_add_label(&enc, "op_open_pop_path");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_call_label(&enc, "open_file_handle");
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_read");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_NUMBER);
    z80_jr_cc_label(&enc, CC_NZ, "op_read_nil");
    z80_call_label(&enc, "read_from_handle");
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");
    z80_add_label(&enc, "op_read_nil");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_write");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_ld_mem_hl_label(&enc, "io_data_ptr");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_NUMBER);
    z80_jr_cc_label(&enc, CC_NZ, "op_write_false");
    z80_call_label(&enc, "write_to_handle");
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");
    z80_add_label(&enc, "op_write_false");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_close");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_NUMBER);
    z80_jr_cc_label(&enc, CC_NZ, "op_close_false");
    z80_call_label(&enc, "close_handle");
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");
    z80_add_label(&enc, "op_close_false");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_concat");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_ld_mem_hl_label(&enc, "concat_right_ptr");
    z80_call_label(&enc, "vstack_pop");
    z80_call_label(&enc, "coerce_to_string");
    z80_ld_de_mem_label(&enc, "concat_right_ptr");
    z80_call_label(&enc, "alloc_concat_string");
    z80_ld_r_n(&enc, REG_A, TYPE_STRING);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "alloc_runtime_space");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "alloc_runtime_space_nonzero");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "alloc_runtime_space_fail");
    z80_add_label(&enc, "alloc_runtime_space_nonzero");
    z80_ld_de_mem_label(&enc, "closure_ptr");
    z80_ex_de_hl(&enc);
    z80_push(&enc, RP_HL);
    z80_add_hl_rp(&enc, RP_DE);
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_DE, "closure_end");
    z80_or_a(&enc);
    z80_sbc_hl_rp(&enc, RP_DE);
    z80_jr_cc_label(&enc, CC_C, "alloc_runtime_space_ok");
    z80_jr_cc_label(&enc, CC_Z, "alloc_runtime_space_ok");
    z80_pop(&enc, RP_HL);
    z80_pop(&enc, RP_HL);
    z80_add_label(&enc, "alloc_runtime_space_fail");
    z80_ld_hl_mem_label(&enc, "alloc_fail_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_fail_count");
    z80_ld_hl_mem_label(&enc, "alloc_closure_fail_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_closure_fail_count");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ret(&enc);
    z80_add_label(&enc, "alloc_runtime_space_ok");
    z80_pop(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "closure_ptr");
    z80_pop(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "alloc_total_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_total_count");
    z80_pop(&enc, RP_HL);
    z80_call_label(&enc, "note_alloc_addr");
    z80_ret(&enc);

    z80_add_label(&enc, "note_alloc_addr");
    z80_push(&enc, RP_HL);
    z80_ld_de_mem_label(&enc, "gc_high_watermark");
    z80_or_a(&enc);
    z80_sbc_hl_rp(&enc, RP_DE);
    z80_jr_cc_label(&enc, CC_C, "note_alloc_addr_check_low");
    z80_jr_cc_label(&enc, CC_Z, "note_alloc_addr_check_low");
    z80_pop(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "gc_high_watermark");

    z80_add_label(&enc, "note_alloc_addr_check_low");
    z80_pop(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_de_mem_label(&enc, "gc_low_watermark");
    z80_ld_r_r(&enc, REG_A, REG_D);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "note_alloc_addr_low_has_value");
    z80_ld_r_r(&enc, REG_A, REG_E);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "note_alloc_addr_low_has_value");
    z80_pop(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "gc_low_watermark");
    z80_jr_label(&enc, "note_alloc_addr_done");

    z80_add_label(&enc, "note_alloc_addr_low_has_value");
    z80_or_a(&enc);
    z80_sbc_hl_rp(&enc, RP_DE);
    z80_jr_cc_label(&enc, CC_NC, "note_alloc_addr_done");
    z80_pop(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "gc_low_watermark");

    z80_add_label(&enc, "note_alloc_addr_done");
    z80_pop(&enc, RP_HL);
    z80_ret(&enc);

    z80_add_label(&enc, "get_captured_cell_ptr");
    z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_n(&enc, REG_H, 0);
    z80_ld_r_r(&enc, REG_E, REG_L);
    z80_ld_r_r(&enc, REG_D, REG_H);
    z80_add_hl_rp(&enc, RP_HL);
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_de_mem_label(&enc, "current_env_ptr");
    z80_add_hl_rp(&enc, RP_DE);
    z80_ret(&enc);

    z80_add_label(&enc, "get_upvalue_cell_ptr");
    z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_n(&enc, REG_H, 0);
    z80_add_hl_rp(&enc, RP_HL);
    z80_ld_de_mem_label(&enc, "current_closure_ptr");
    z80_add_hl_rp(&enc, RP_DE);
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_ret(&enc);

    z80_add_label(&enc, "instantiate_closure");
    z80_ld_mem_hl_label(&enc, "closure_source_ptr");
    z80_push(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "instantiate_closure_alloc");
    z80_pop(&enc, RP_HL);
    z80_ret(&enc);
    z80_add_label(&enc, "instantiate_closure_alloc");
    z80_ld_r_r(&enc, REG_C, REG_A);
    z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_n(&enc, REG_H, 0);
    z80_add_hl_rp(&enc, RP_HL);
    z80_ld_rp_nn(&enc, RP_DE, FUNCTION_HEADER_BYTES);
    z80_add_hl_rp(&enc, RP_DE);
    z80_call_label(&enc, "alloc_runtime_space");
    z80_ld_mem_hl_label(&enc, "closure_candidate");
    z80_ld_de_mem_label(&enc, "closure_candidate");
    z80_pop(&enc, RP_HL);
    z80_ld_r_n(&enc, REG_B, FUNCTION_HEADER_BYTES);
    z80_add_label(&enc, "closure_header_copy");
    z80_ld_a_hl(&enc);
    z80_emit_b(&enc, 0x12);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_DE);
    z80_djnz_label(&enc, "closure_header_copy");
    z80_ld_r_r(&enc, REG_B, REG_C);
    z80_add_label(&enc, "closure_capture_loop");
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "closure_capture_done");
    z80_ld_a_hl(&enc);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_push(&enc, RP_DE);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "closure_capture_parent");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_call_label(&enc, "get_captured_cell_ptr");
    z80_jr_label(&enc, "closure_capture_store");
    z80_add_label(&enc, "closure_capture_parent");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_call_label(&enc, "get_upvalue_cell_ptr");
    z80_add_label(&enc, "closure_capture_store");
    z80_pop(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_emit_b(&enc, 0x12);
    z80_inc_rp(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_emit_b(&enc, 0x12);
    z80_inc_rp(&enc, RP_DE);
    z80_pop(&enc, RP_HL);
    z80_djnz_label(&enc, "closure_capture_loop");
    z80_add_label(&enc, "closure_capture_done");
    z80_ld_hl_mem_label(&enc, "closure_candidate");
    z80_ret(&enc);

    z80_add_label(&enc, "op_closure");
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_ld_r_r(&enc, REG_L, REG_A); z80_ld_r_n(&enc, REG_H, 0); z80_ld_r_r(&enc, REG_E, REG_L); z80_ld_r_r(&enc, REG_D, REG_H); z80_add_hl_rp(&enc, RP_HL); z80_add_hl_rp(&enc, RP_DE);
    z80_ld_de_mem_label(&enc, "cp_ptr"); z80_add_hl_rp(&enc, RP_DE);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_call_label(&enc, "instantiate_closure");
    z80_ld_r_n(&enc, REG_A, TYPE_FUNCTION);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_call");
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_ld_r_r(&enc, REG_B, REG_A);
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_call_label(&enc, "cstack_push_hl");
    z80_ld_hl_mem_label(&enc, "fp_ptr"); z80_call_label(&enc, "cstack_push_hl");
    z80_ld_hl_mem_label(&enc, "cp_ptr"); z80_call_label(&enc, "cstack_push_hl");
    z80_ld_hl_mem_label(&enc, "current_env_ptr"); z80_call_label(&enc, "cstack_push_hl");
    z80_ld_hl_mem_label(&enc, "current_closure_ptr"); z80_call_label(&enc, "cstack_push_hl");
    z80_ld_hl_mem_label(&enc, "vsp_ptr");
    z80_add_label(&enc, "call_frame_seek");
    z80_ld_r_r(&enc, REG_A, REG_B); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_Z, "call_frame_found");
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_djnz_label(&enc, "call_frame_seek");
    z80_add_label(&enc, "call_frame_found");
    z80_ld_mem_hl_label(&enc, "call_frame_temp");
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "fp_ptr");
    z80_ld_hl_mem_label(&enc, "call_frame_temp");
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "call_func_temp");
    z80_ld_hl_mem_label(&enc, "call_func_temp");
    z80_ld_mem_hl_label(&enc, "current_closure_ptr");
    z80_ld_hl_mem_label(&enc, "call_func_temp");
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_ld_hl_mem_label(&enc, "call_func_temp");
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "cp_ptr");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_mem_hl_label(&enc, "current_env_ptr");
    z80_ld_hl_mem_label(&enc, "call_func_temp");
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "call_env_ready");
    z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_n(&enc, REG_H, 0);
    z80_ld_r_r(&enc, REG_E, REG_L);
    z80_ld_r_r(&enc, REG_D, REG_H);
    z80_add_hl_rp(&enc, RP_HL);
    z80_add_hl_rp(&enc, RP_DE);
    z80_call_label(&enc, "alloc_runtime_space");
    z80_ld_mem_hl_label(&enc, "current_env_ptr");
    z80_add_label(&enc, "call_env_ready");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_return");
    z80_ld_hl_mem_label(&enc, "pc_ptr"); z80_inc_rp(&enc, RP_HL); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "return_temp");
    z80_ld_rp_label(&enc, RP_HL, "return_type");
    z80_ld_hl_a(&enc);
    z80_ld_hl_mem_label(&enc, "fp_ptr");
    z80_ld_mem_hl_label(&enc, "vsp_ptr");
    z80_call_label(&enc, "cstack_pop_hl"); z80_ld_mem_hl_label(&enc, "current_closure_ptr");
    z80_call_label(&enc, "cstack_pop_hl"); z80_ld_mem_hl_label(&enc, "current_env_ptr");
    z80_call_label(&enc, "cstack_pop_hl"); z80_ld_mem_hl_label(&enc, "cp_ptr");
    z80_call_label(&enc, "cstack_pop_hl"); z80_ld_mem_hl_label(&enc, "fp_ptr");
    z80_call_label(&enc, "cstack_pop_hl"); z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_ld_hl_mem_label(&enc, "return_temp");
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_HL, "return_type");
    z80_ld_a_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");
}

static void emit_print_and_string_ops(void) {
    z80_add_label(&enc, "print_num");
    z80_ld_rp_label(&enc, RP_DE, "num_buffer_end");
    z80_ld_rp_nn(&enc, RP_BC, 10);
    z80_add_label(&enc, "print_num_loop");
    z80_call_label(&enc, "div16_8");
    z80_add_a_n(&enc, '0'); z80_dec_rp(&enc, RP_DE);
    z80_emit_b(&enc, 0x12);
    z80_ld_r_r(&enc, REG_A, REG_H); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "print_num_loop");
    z80_ld_r_r(&enc, REG_A, REG_L); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "print_num_loop");
    z80_ex_de_hl(&enc); z80_call_label(&enc, "print_zstr");
    z80_ret(&enc);

    z80_add_label(&enc, "print_zstr");
    z80_push(&enc, RP_HL); z80_ld_r_n(&enc, REG_B, 0);
    z80_add_label(&enc, "ps_len"); z80_ld_a_hl(&enc); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_Z, "ps_out");
    z80_inc_rp(&enc, RP_HL); z80_inc_r(&enc, REG_B); z80_jr_label(&enc, "ps_len");
    z80_add_label(&enc, "ps_out"); 
    z80_pop(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_C, REG_B); z80_ld_r_n(&enc, REG_B, 0); 
    z80_ld_rp_nn(&enc, RP_HL, 1);  // H=STDOUT=0, L=1 ZEAL SYSCALL WRITE
    z80_rst(&enc, 0x08); z80_ret(&enc);

    z80_add_label(&enc, "print_str");
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ex_de_hl(&enc);
    z80_ld_rp_nn(&enc, RP_HL, 1);  // H=STDOUT=0, L=1 ZEAL SYSCALL WRITE
    z80_rst(&enc, 0x08); z80_ret(&enc);

    z80_add_label(&enc, "div16_8");
    z80_xor_a(&enc); z80_ld_r_n(&enc, REG_B, 16);
    z80_add_label(&enc, "div_l"); z80_add_hl_rp(&enc, RP_HL); z80_emit_b(&enc, 0x17);
    z80_cp_a_n(&enc, 10); z80_jr_cc_label(&enc, CC_C, "div_s");
    z80_sub_a_n(&enc, 10); z80_inc_r(&enc, REG_L);
    z80_add_label(&enc, "div_s"); z80_djnz_label(&enc, "div_l"); z80_ret(&enc);

    z80_add_label(&enc, "divmod10_u16");
    z80_ld_rp_nn(&enc, RP_DE, 0);
    z80_add_label(&enc, "divmod10_u16_loop");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "divmod10_u16_subtract");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_cp_a_n(&enc, 10);
    z80_jr_cc_label(&enc, CC_C, "divmod10_u16_done");
    z80_add_label(&enc, "divmod10_u16_subtract");
    z80_push(&enc, RP_DE);
    z80_ld_rp_nn(&enc, RP_DE, 10);
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_pop(&enc, RP_DE);
    z80_inc_rp(&enc, RP_DE);
    z80_jr_label(&enc, "divmod10_u16_loop");
    z80_add_label(&enc, "divmod10_u16_done");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_ex_de_hl(&enc);
    z80_ret(&enc);

    z80_add_label(&enc, "number_to_string");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_emit_b(&enc, 0xE6); z80_emit_b(&enc, 0x80);
    z80_jr_cc_label(&enc, CC_Z, "number_to_string_positive");
    z80_ld_r_r(&enc, REG_A, REG_L); z80_emit_b(&enc, 0x2F); z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_r(&enc, REG_A, REG_H); z80_emit_b(&enc, 0x2F); z80_ld_r_r(&enc, REG_H, REG_A);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_DE, "tostring_negative");
    z80_ld_r_n(&enc, REG_A, 1);
    z80_emit_b(&enc, 0x12);
    z80_jr_label(&enc, "number_to_string_start");
    z80_add_label(&enc, "number_to_string_positive");
    z80_ld_rp_label(&enc, RP_DE, "tostring_negative");
    z80_xor_a(&enc);
    z80_emit_b(&enc, 0x12);
    z80_add_label(&enc, "number_to_string_start");
    z80_ld_rp_label(&enc, RP_DE, "num_buffer_end");
    z80_add_label(&enc, "number_to_string_loop");
    z80_push(&enc, RP_DE);
    z80_call_label(&enc, "divmod10_u16");
    z80_pop(&enc, RP_DE);
    z80_add_a_n(&enc, '0'); z80_dec_rp(&enc, RP_DE);
    z80_emit_b(&enc, 0x12);
    z80_ld_r_r(&enc, REG_A, REG_H); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "number_to_string_loop");
    z80_ld_r_r(&enc, REG_A, REG_L); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "number_to_string_loop");
    z80_ld_rp_label(&enc, RP_HL, "tostring_negative");
    z80_ld_a_hl(&enc); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_Z, "number_to_string_done");
    z80_dec_rp(&enc, RP_DE);
    z80_ld_r_n(&enc, REG_A, '-');
    z80_emit_b(&enc, 0x12);
    z80_add_label(&enc, "number_to_string_done");
    z80_ld_rp_label(&enc, RP_HL, "num_buffer_end");
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_ex_de_hl(&enc);
    z80_call_label(&enc, "alloc_raw_string");
    z80_ret(&enc);

    z80_add_label(&enc, "alloc_string_copy");
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_call_label(&enc, "alloc_raw_string");
    z80_ret(&enc);

    z80_add_label(&enc, "alloc_raw_string");
    z80_ld_mem_hl_label(&enc, "string_source");
    z80_ex_de_hl(&enc);
    z80_call_label(&enc, "alloc_string_space");
    z80_ld_r_r(&enc, REG_A, REG_D);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "alloc_raw_string_copy");
    z80_ld_r_r(&enc, REG_A, REG_E);
    z80_or_a(&enc);
    z80_ret(&enc);
    z80_add_label(&enc, "alloc_raw_string_copy");
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "string_length");
    z80_ld_r_r(&enc, REG_B, REG_H);
    z80_ld_r_r(&enc, REG_C, REG_L);
    z80_ld_hl_mem_label(&enc, "string_source");
    z80_call_label(&enc, "copy_bc_bytes");
    z80_xor_a(&enc);
    z80_emit_b(&enc, 0x12);
    z80_pop(&enc, RP_HL);
    z80_ret(&enc);

    z80_add_label(&enc, "alloc_string_space");
    z80_ld_mem_hl_label(&enc, "string_length");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "alloc_string_space_non_empty");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "alloc_string_space_empty");
    z80_add_label(&enc, "alloc_string_space_non_empty");
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ex_de_hl(&enc);
    z80_ld_hl_mem_label(&enc, "string_ptr");
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_mem_hl_label(&enc, "string_candidate");
    z80_ex_de_hl(&enc);
    z80_ld_rp_label(&enc, RP_HL, "string_end");
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_jr_cc_label(&enc, CC_C, "alloc_string_space_empty");
    z80_ld_hl_mem_label(&enc, "string_ptr");
    z80_push(&enc, RP_HL);
    z80_ld_de_mem_label(&enc, "string_length");
    z80_ld_r_r(&enc, REG_M, REG_E);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_M, REG_D);
    z80_inc_rp(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "string_candidate");
    z80_ld_mem_hl_label(&enc, "string_ptr");
    z80_pop(&enc, RP_DE);
    z80_pop(&enc, RP_HL);
    z80_push(&enc, RP_DE);
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "alloc_total_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_total_count");
    z80_pop(&enc, RP_HL);
    z80_call_label(&enc, "note_alloc_addr");
    z80_pop(&enc, RP_DE);
    z80_ret(&enc);
    z80_add_label(&enc, "alloc_string_space_empty");
    z80_ld_hl_mem_label(&enc, "alloc_fail_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_fail_count");
    z80_ld_hl_mem_label(&enc, "alloc_string_fail_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_string_fail_count");
    z80_ld_rp_label(&enc, RP_HL, "str_empty");
    z80_ld_rp_nn(&enc, RP_DE, 0);
    z80_ret(&enc);

    z80_add_label(&enc, "alloc_concat_string");
    z80_ld_mem_hl_label(&enc, "concat_left_ptr");
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "concat_right_ptr");
    z80_ld_hl_mem_label(&enc, "concat_left_ptr");
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "concat_left_len");
    z80_ld_hl_mem_label(&enc, "concat_right_ptr");
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "concat_right_len");
    z80_ld_hl_mem_label(&enc, "concat_left_len");
    z80_ld_de_mem_label(&enc, "concat_right_len");
    z80_add_hl_rp(&enc, RP_DE);
    z80_call_label(&enc, "alloc_string_space");
    z80_ld_r_r(&enc, REG_A, REG_D);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "alloc_concat_copy");
    z80_ld_r_r(&enc, REG_A, REG_E);
    z80_or_a(&enc);
    z80_ret(&enc);
    z80_add_label(&enc, "alloc_concat_copy");
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "concat_left_len");
    z80_ld_r_r(&enc, REG_B, REG_H);
    z80_ld_r_r(&enc, REG_C, REG_L);
    z80_ld_hl_mem_label(&enc, "concat_left_ptr");
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_call_label(&enc, "copy_bc_bytes");
    z80_ld_hl_mem_label(&enc, "concat_right_len");
    z80_ld_r_r(&enc, REG_B, REG_H);
    z80_ld_r_r(&enc, REG_C, REG_L);
    z80_ld_hl_mem_label(&enc, "concat_right_ptr");
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_call_label(&enc, "copy_bc_bytes");
    z80_xor_a(&enc);
    z80_emit_b(&enc, 0x12);
    z80_pop(&enc, RP_HL);
    z80_ret(&enc);

    z80_add_label(&enc, "copy_bc_bytes");
    z80_add_label(&enc, "copy_bc_bytes_check");
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "copy_bc_bytes_body");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "copy_bc_bytes_done");
    z80_add_label(&enc, "copy_bc_bytes_body");
    z80_ld_a_hl(&enc);
    z80_emit_b(&enc, 0x12);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_DE);
    z80_dec_rp(&enc, RP_BC);
    z80_jr_label(&enc, "copy_bc_bytes_check");
    z80_add_label(&enc, "copy_bc_bytes_done");
    z80_ret(&enc);

    z80_add_label(&enc, "read_line_string");
    z80_ld_rp_label(&enc, RP_DE, "input_buffer");
    z80_ld_rp_nn(&enc, RP_BC, 63);
    z80_ld_rp_nn(&enc, RP_HL, 0x0100);
    z80_rst(&enc, 0x08);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_line_string_nil");
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_line_string_have_bytes");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "read_line_string_nil");
    z80_add_label(&enc, "read_line_string_have_bytes");
    z80_ld_rp_label(&enc, RP_HL, "input_buffer");
    z80_add_hl_rp(&enc, RP_BC);
    z80_dec_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, '\n');
    z80_jr_cc_label(&enc, CC_NZ, "read_line_string_check_cr");
    z80_dec_rp(&enc, RP_BC);
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_line_string_after_lf");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "read_line_string_ready");
    z80_add_label(&enc, "read_line_string_after_lf");
    z80_dec_rp(&enc, RP_HL);
    z80_add_label(&enc, "read_line_string_check_cr");
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, '\r');
    z80_jr_cc_label(&enc, CC_NZ, "read_line_string_ready");
    z80_dec_rp(&enc, RP_BC);
    z80_add_label(&enc, "read_line_string_ready");
    z80_ld_r_r(&enc, REG_D, REG_B);
    z80_ld_r_r(&enc, REG_E, REG_C);
    z80_ld_rp_label(&enc, RP_HL, "input_buffer");
    z80_call_label(&enc, "alloc_raw_string");
    z80_ld_r_n(&enc, REG_A, TYPE_STRING);
    z80_ret(&enc);
    z80_add_label(&enc, "read_line_string_nil");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_ret(&enc);

    z80_add_label(&enc, "read_file_string");
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_C, REG_L);
    z80_ld_r_r(&enc, REG_B, REG_H);
    z80_ld_rp_nn(&enc, RP_HL, 0x0002);
    z80_rst(&enc, 0x08);
    z80_cp_a_n(&enc, 0x80);
    z80_jr_cc_label(&enc, CC_NC, "read_file_string_fail");
    z80_ld_rp_label(&enc, RP_HL, "readfile_dev");
    z80_ld_hl_a(&enc);

    z80_ld_r_r(&enc, REG_H, REG_A);
    z80_ld_r_n(&enc, REG_L, 0);
    z80_ld_rp_label(&enc, RP_DE, "input_buffer");
    z80_ld_rp_nn(&enc, RP_BC, 63);
    z80_rst(&enc, 0x08);
    z80_push(&enc, RP_AF);

    z80_ld_rp_label(&enc, RP_HL, "readfile_dev");
    z80_ld_a_hl(&enc);
    z80_ld_r_r(&enc, REG_H, REG_A);
    z80_ld_r_n(&enc, REG_L, 3);
    z80_rst(&enc, 0x08);

    z80_pop(&enc, RP_AF);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_file_string_fail");
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_file_string_make");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_file_string_make");
    z80_ld_rp_label(&enc, RP_HL, "str_empty");
    z80_ld_r_n(&enc, REG_A, TYPE_STRING);
    z80_ret(&enc);

    z80_add_label(&enc, "read_file_string_make");
    z80_ld_r_r(&enc, REG_D, REG_B);
    z80_ld_r_r(&enc, REG_E, REG_C);
    z80_ld_rp_label(&enc, RP_HL, "input_buffer");
    z80_call_label(&enc, "alloc_raw_string");
    z80_ld_r_n(&enc, REG_A, TYPE_STRING);
    z80_ret(&enc);

    z80_add_label(&enc, "read_file_string_fail");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_ret(&enc);

    z80_add_label(&enc, "write_file_string");
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_C, REG_L);
    z80_ld_r_r(&enc, REG_B, REG_H);
    z80_ld_rp_nn(&enc, RP_HL, 0x1502);
    z80_rst(&enc, 0x08);
    z80_cp_a_n(&enc, 0x80);
    z80_jr_cc_label(&enc, CC_NC, "write_file_string_false");
    z80_ld_rp_label(&enc, RP_HL, "writefile_dev");
    z80_ld_hl_a(&enc);

    z80_ld_hl_mem_label(&enc, "writefile_data_ptr");
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ex_de_hl(&enc);
    z80_ld_rp_label(&enc, RP_HL, "writefile_dev");
    z80_ld_a_hl(&enc);
    z80_ld_r_r(&enc, REG_H, REG_A);
    z80_ld_r_n(&enc, REG_L, 1);
    z80_rst(&enc, 0x08);
    z80_push(&enc, RP_AF);

    z80_ld_rp_label(&enc, RP_HL, "writefile_dev");
    z80_ld_a_hl(&enc);
    z80_ld_r_r(&enc, REG_H, REG_A);
    z80_ld_r_n(&enc, REG_L, 3);
    z80_rst(&enc, 0x08);

    z80_pop(&enc, RP_AF);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "write_file_string_false");
    z80_ld_rp_nn(&enc, RP_HL, 1);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_ret(&enc);

    z80_add_label(&enc, "write_file_string_false");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_ret(&enc);

    z80_add_label(&enc, "open_file_handle");
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_C, REG_L);
    z80_ld_r_r(&enc, REG_B, REG_H);
    z80_ld_rp_label(&enc, RP_HL, "open_flags");
    z80_ld_a_hl(&enc);
    z80_ld_r_r(&enc, REG_H, REG_A);
    z80_ld_r_n(&enc, REG_L, 2);
    z80_rst(&enc, 0x08);
    z80_cp_a_n(&enc, 0x80);
    z80_jr_cc_label(&enc, CC_NC, "open_file_handle_fail");
    z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_n(&enc, REG_H, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NUMBER);
    z80_ret(&enc);
    z80_add_label(&enc, "open_file_handle_fail");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_ret(&enc);

    z80_add_label(&enc, "read_from_handle");
    z80_ld_r_r(&enc, REG_H, REG_L);
    z80_ld_r_n(&enc, REG_L, 0);
    z80_ld_rp_label(&enc, RP_DE, "input_buffer");
    z80_ld_rp_nn(&enc, RP_BC, 63);
    z80_rst(&enc, 0x08);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_from_handle_fail");
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "read_from_handle_make");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "read_from_handle_fail");
    z80_add_label(&enc, "read_from_handle_make");
    z80_ld_r_r(&enc, REG_D, REG_B);
    z80_ld_r_r(&enc, REG_E, REG_C);
    z80_ld_rp_label(&enc, RP_HL, "input_buffer");
    z80_call_label(&enc, "alloc_raw_string");
    z80_ld_r_n(&enc, REG_A, TYPE_STRING);
    z80_ret(&enc);
    z80_add_label(&enc, "read_from_handle_fail");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_ret(&enc);

    z80_add_label(&enc, "write_to_handle");
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "io_data_ptr");
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ex_de_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_H, REG_L);
    z80_ld_r_n(&enc, REG_L, 1);
    z80_rst(&enc, 0x08);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "write_to_handle_fail");
    z80_ld_rp_nn(&enc, RP_HL, 1);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_ret(&enc);
    z80_add_label(&enc, "write_to_handle_fail");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_ret(&enc);

    z80_add_label(&enc, "close_handle");
    z80_ld_r_r(&enc, REG_H, REG_L);
    z80_ld_r_n(&enc, REG_L, 3);
    z80_rst(&enc, 0x08);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "close_handle_fail");
    z80_ld_rp_nn(&enc, RP_HL, 1);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_ret(&enc);
    z80_add_label(&enc, "close_handle_fail");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_BOOL);
    z80_ret(&enc);

    z80_add_label(&enc, "coerce_to_string");
    z80_cp_a_n(&enc, TYPE_STRING);
    z80_jr_cc_label(&enc, CC_Z, "coerce_to_string_return");
    z80_cp_a_n(&enc, TYPE_NUMBER); z80_jr_cc_label(&enc, CC_Z, "coerce_to_string_number");
    z80_cp_a_n(&enc, TYPE_NIL); z80_jr_cc_label(&enc, CC_Z, "coerce_to_string_nil");
    z80_cp_a_n(&enc, TYPE_BOOL); z80_jr_cc_label(&enc, CC_Z, "coerce_to_string_bool");
    z80_cp_a_n(&enc, TYPE_TABLE); z80_jr_cc_label(&enc, CC_Z, "coerce_to_string_table");
    z80_ld_rp_label(&enc, RP_HL, "str_function_value");
    z80_ret(&enc);
    z80_add_label(&enc, "coerce_to_string_nil");
    z80_ld_rp_label(&enc, RP_HL, "str_nil_value");
    z80_ret(&enc);
    z80_add_label(&enc, "coerce_to_string_bool");
    z80_ld_r_r(&enc, REG_A, REG_H); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "coerce_to_string_true");
    z80_ld_r_r(&enc, REG_A, REG_L); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "coerce_to_string_true");
    z80_ld_rp_label(&enc, RP_HL, "str_false_value");
    z80_ret(&enc);
    z80_add_label(&enc, "coerce_to_string_true");
    z80_ld_rp_label(&enc, RP_HL, "str_true_value");
    z80_ret(&enc);
    z80_add_label(&enc, "coerce_to_string_table");
    z80_ld_rp_label(&enc, RP_HL, "str_table_value");
    z80_ret(&enc);
    z80_add_label(&enc, "coerce_to_string_number");
    z80_call_label(&enc, "number_to_string");
    z80_add_label(&enc, "coerce_to_string_return");
    z80_ret(&enc);

    z80_add_label(&enc, "string_to_number");
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "tonumber_remaining");
    z80_pop(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "tonumber_ptr");
    z80_ld_rp_label(&enc, RP_DE, "tonumber_negative");
    z80_xor_a(&enc);
    z80_emit_b(&enc, 0x12);
    z80_ld_hl_mem_label(&enc, "tonumber_remaining");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "string_to_number_have_chars");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "string_to_number_fail");
    z80_add_label(&enc, "string_to_number_have_chars");
    z80_ld_hl_mem_label(&enc, "tonumber_ptr");
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, '-');
    z80_jr_cc_label(&enc, CC_NZ, "string_to_number_after_sign");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "tonumber_ptr");
    z80_ld_hl_mem_label(&enc, "tonumber_remaining");
    z80_dec_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "tonumber_remaining");
    z80_ld_rp_label(&enc, RP_DE, "tonumber_negative");
    z80_ld_r_n(&enc, REG_A, 1);
    z80_emit_b(&enc, 0x12);
    z80_add_label(&enc, "string_to_number_after_sign");
    z80_ld_hl_mem_label(&enc, "tonumber_remaining");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "string_to_number_init");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "string_to_number_fail");
    z80_add_label(&enc, "string_to_number_init");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_mem_hl_label(&enc, "tonumber_result");
    z80_add_label(&enc, "string_to_number_loop");
    z80_ld_hl_mem_label(&enc, "tonumber_remaining");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "string_to_number_read_char");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "string_to_number_done_digits");
    z80_add_label(&enc, "string_to_number_read_char");
    z80_ld_hl_mem_label(&enc, "tonumber_ptr");
    z80_ld_a_hl(&enc);
    z80_sub_a_n(&enc, '0');
    z80_cp_a_n(&enc, 10);
    z80_jr_cc_label(&enc, CC_NC, "string_to_number_fail");
    z80_ld_r_r(&enc, REG_C, REG_A);
    z80_ld_hl_mem_label(&enc, "tonumber_result");
    z80_ld_rp_nn(&enc, RP_DE, 10);
    z80_call_label(&enc, "mul16");
    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_ld_r_r(&enc, REG_E, REG_A);
    z80_ld_r_n(&enc, REG_D, 0);
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_mem_hl_label(&enc, "tonumber_result");
    z80_ld_hl_mem_label(&enc, "tonumber_ptr");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "tonumber_ptr");
    z80_ld_hl_mem_label(&enc, "tonumber_remaining");
    z80_dec_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "tonumber_remaining");
    z80_jr_label(&enc, "string_to_number_loop");
    z80_add_label(&enc, "string_to_number_done_digits");
    z80_ld_hl_mem_label(&enc, "tonumber_result");
    z80_ld_rp_label(&enc, RP_DE, "tonumber_negative");
    z80_emit_b(&enc, 0x1A);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "string_to_number_success");
    z80_ld_r_r(&enc, REG_A, REG_L); z80_emit_b(&enc, 0x2F); z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_r(&enc, REG_A, REG_H); z80_emit_b(&enc, 0x2F); z80_ld_r_r(&enc, REG_H, REG_A);
    z80_inc_rp(&enc, RP_HL);
    z80_add_label(&enc, "string_to_number_success");
    z80_ld_r_n(&enc, REG_A, 1);
    z80_ret(&enc);
    z80_add_label(&enc, "string_to_number_fail");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_xor_a(&enc);
    z80_ret(&enc);
}

static void emit_numeric_and_misc_ops(void) {
    z80_add_label(&enc, "op_add");
    z80_call_label(&enc, "vstack_pop"); z80_push(&enc, RP_AF); z80_push(&enc, RP_HL);
    z80_call_label(&enc, "vstack_pop"); z80_pop(&enc, RP_DE);
    z80_add_hl_rp(&enc, RP_DE);
    z80_pop(&enc, RP_AF);
    z80_call_label(&enc, "vstack_push"); z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_sub");
    z80_call_label(&enc, "vstack_pop"); z80_push(&enc, RP_AF); z80_push(&enc, RP_HL);
    z80_call_label(&enc, "vstack_pop"); z80_pop(&enc, RP_DE);
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_pop(&enc, RP_AF);
    z80_call_label(&enc, "vstack_push"); z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_jump");
    z80_ld_hl_mem_label(&enc, "pc_ptr");
    z80_ld_a_hl(&enc); z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_H, REG_M); z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_de_mem_label(&enc, "pc_ptr");
    z80_inc_rp(&enc, RP_DE); z80_inc_rp(&enc, RP_DE);
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_mem_hl_label(&enc, "pc_ptr");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_mul");
    z80_call_label(&enc, "vstack_pop"); z80_push(&enc, RP_HL);
    z80_call_label(&enc, "vstack_pop"); z80_pop(&enc, RP_DE);
    z80_call_label(&enc, "mul16");
    z80_ld_r_n(&enc, REG_A, 2); z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_div");
    z80_call_label(&enc, "vstack_pop"); z80_push(&enc, RP_HL);
    z80_call_label(&enc, "vstack_pop"); z80_pop(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_A, REG_D); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "div_nonzero");
    z80_ld_r_r(&enc, REG_A, REG_E); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_Z, "div_zero");
    z80_add_label(&enc, "div_nonzero");
    z80_ld_rp_nn(&enc, RP_BC, 0);
    z80_add_label(&enc, "div_loop16");
    z80_xor_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_jr_cc_label(&enc, CC_C, "div_done16");
    z80_inc_rp(&enc, RP_BC);
    z80_jr_label(&enc, "div_loop16");
    z80_add_label(&enc, "div_done16");
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_H, REG_B); z80_ld_r_r(&enc, REG_L, REG_C);
    z80_jr_label(&enc, "div_push16");
    z80_add_label(&enc, "div_zero");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_add_label(&enc, "div_push16");
    z80_ld_r_n(&enc, REG_A, 2); z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_mod");
    z80_call_label(&enc, "vstack_pop"); z80_push(&enc, RP_HL);
    z80_call_label(&enc, "vstack_pop"); z80_pop(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_A, REG_D); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "mod_nonzero");
    z80_ld_r_r(&enc, REG_A, REG_E); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_Z, "mod_zero");
    z80_add_label(&enc, "mod_nonzero");
    z80_add_label(&enc, "mod_loop16");
    z80_xor_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_jr_cc_label(&enc, CC_C, "mod_done16");
    z80_jr_label(&enc, "mod_loop16");
    z80_add_label(&enc, "mod_done16");
    z80_add_hl_rp(&enc, RP_DE);
    z80_jr_label(&enc, "mod_push16");
    z80_add_label(&enc, "mod_zero");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_add_label(&enc, "mod_push16");
    z80_ld_r_n(&enc, REG_A, 2); z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_pow");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "pow_exp");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "pow_base");
    z80_ld_hl_mem_label(&enc, "pow_exp");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_emit_b(&enc, 0xE6); z80_emit_b(&enc, 0x80);
    z80_jr_cc_label(&enc, CC_Z, "pow_non_negative");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_jr_label(&enc, "pow_push");
    z80_add_label(&enc, "pow_non_negative");
    z80_ld_rp_nn(&enc, RP_HL, 1);
    z80_ld_mem_hl_label(&enc, "pow_result");
    z80_add_label(&enc, "pow_loop_check");
    z80_ld_hl_mem_label(&enc, "pow_exp");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "pow_loop_body");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "pow_done");
    z80_add_label(&enc, "pow_loop_body");
    z80_ld_hl_mem_label(&enc, "pow_result");
    z80_ld_de_mem_label(&enc, "pow_base");
    z80_call_label(&enc, "mul16");
    z80_ld_mem_hl_label(&enc, "pow_result");
    z80_ld_hl_mem_label(&enc, "pow_exp");
    z80_dec_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "pow_exp");
    z80_jr_label(&enc, "pow_loop_check");
    z80_add_label(&enc, "pow_done");
    z80_ld_hl_mem_label(&enc, "pow_result");
    z80_add_label(&enc, "pow_push");
    z80_ld_r_n(&enc, REG_A, TYPE_NUMBER);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_neg");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_r_r(&enc, REG_A, REG_L); z80_emit_b(&enc, 0x2F); z80_ld_r_r(&enc, REG_L, REG_A);
    z80_ld_r_r(&enc, REG_A, REG_H); z80_emit_b(&enc, 0x2F); z80_ld_r_r(&enc, REG_H, REG_A);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_n(&enc, REG_A, 2); z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_not");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, 1);
    z80_jr_cc_label(&enc, CC_Z, "not_bool");
    z80_or_a(&enc); z80_jr_cc_label(&enc, CC_Z, "not_true");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_jr_label(&enc, "not_push");
    z80_add_label(&enc, "not_bool");
    z80_ld_r_r(&enc, REG_A, REG_H); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_NZ, "not_false");
    z80_ld_r_r(&enc, REG_A, REG_L); z80_or_a(&enc); z80_jr_cc_label(&enc, CC_Z, "not_true");
    z80_add_label(&enc, "not_false");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_jr_label(&enc, "not_push");
    z80_add_label(&enc, "not_true");
    z80_ld_rp_nn(&enc, RP_HL, 1);
    z80_add_label(&enc, "not_push");
    z80_ld_r_n(&enc, REG_A, 1); z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_len");
    z80_call_label(&enc, "vstack_pop");
    z80_cp_a_n(&enc, TYPE_STRING);
    z80_jr_cc_label(&enc, CC_Z, "len_string");
    z80_cp_a_n(&enc, TYPE_TABLE);
    z80_jr_cc_label(&enc, CC_Z, "len_table");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_jr_label(&enc, "len_push");

    z80_add_label(&enc, "len_string");
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_jr_label(&enc, "len_push");

    z80_add_label(&enc, "len_table");
    z80_ld_mem_hl_label(&enc, "len_table_ptr");
    z80_ld_rp_nn(&enc, RP_DE, 1);
    z80_add_label(&enc, "len_table_outer");
    z80_ex_de_hl(&enc);
    z80_ld_mem_hl_label(&enc, "len_target");
    z80_ex_de_hl(&enc);
    z80_ld_hl_mem_label(&enc, "len_table_ptr");
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "len_table_not_found");
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_add_label(&enc, "len_table_loop");
    z80_push(&enc, RP_HL);
    z80_push(&enc, RP_BC);
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, TYPE_NUMBER);
    z80_jr_cc_label(&enc, CC_NZ, "len_table_next");
    z80_ld_hl_mem_label(&enc, "len_target");
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x42);
    z80_jr_cc_label(&enc, CC_Z, "len_table_found");
    z80_add_label(&enc, "len_table_next");
    z80_pop(&enc, RP_BC);
    z80_pop(&enc, RP_HL);
    z80_ld_rp_nn(&enc, RP_DE, TABLE_ENTRY_SIZE);
    z80_add_hl_rp(&enc, RP_DE);
    z80_djnz_label(&enc, "len_table_loop");
    z80_jr_label(&enc, "len_table_not_found");
    z80_add_label(&enc, "len_table_found");
    z80_pop(&enc, RP_BC);
    z80_pop(&enc, RP_HL);
    z80_ld_de_mem_label(&enc, "len_target");
    z80_inc_rp(&enc, RP_DE);
    z80_jr_label(&enc, "len_table_outer");
    z80_add_label(&enc, "len_table_not_found");
    z80_ld_hl_mem_label(&enc, "len_target");
    z80_dec_rp(&enc, RP_HL);

    z80_add_label(&enc, "len_push");
    z80_ld_r_n(&enc, REG_A, TYPE_NUMBER);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");
}

static void emit_table_ops(void) {
    z80_add_label(&enc, "alloc_table_object");
    z80_ld_hl_mem_label(&enc, "free_table_list");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "alloc_table_object_from_free");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "alloc_table_object_from_free");

    z80_ld_hl_mem_label(&enc, "heap_ptr");
    z80_push(&enc, RP_HL);
    z80_ld_rp_nn(&enc, RP_DE, TABLE_SIZE);
    z80_add_hl_rp(&enc, RP_DE);
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_DE, "heap_end");
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_jr_cc_label(&enc, CC_C, "alloc_table_object_heap_ok");
    z80_jr_cc_label(&enc, CC_Z, "alloc_table_object_heap_ok");

    z80_pop(&enc, RP_HL);
    z80_pop(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "alloc_fail_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_fail_count");
    z80_ld_hl_mem_label(&enc, "alloc_table_fail_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_table_fail_count");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ret(&enc);

    z80_add_label(&enc, "alloc_table_object_heap_ok");
    z80_pop(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "heap_ptr");
    z80_pop(&enc, RP_HL);
    z80_jr_label(&enc, "alloc_table_object_success");

    z80_add_label(&enc, "alloc_table_object_from_free");
    z80_ld_r_r(&enc, REG_D, REG_H);
    z80_ld_r_r(&enc, REG_E, REG_L);
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_ld_r_r(&enc, REG_H, REG_B);
    z80_ld_r_r(&enc, REG_L, REG_C);
    z80_ld_mem_hl_label(&enc, "free_table_list");
    z80_ex_de_hl(&enc);

    z80_add_label(&enc, "alloc_table_object_success");
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "alloc_total_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "alloc_total_count");
    z80_pop(&enc, RP_HL);
    z80_call_label(&enc, "note_alloc_addr");
    z80_ret(&enc);

    /* Recycle a table object back to the free list.
     * Input: HL = table pointer to reclaim. Preserves all registers except F. */
    z80_add_label(&enc, "free_table_object");
    z80_ld_de_mem_label(&enc, "free_table_list");   /* DE = current free list head */
    z80_ld_r_r(&enc, REG_M, REG_E);                /* (HL)   = lo of old head */
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_M, REG_D);                /* (HL+1) = hi of old head */
    z80_dec_rp(&enc, RP_HL);                        /* restore HL to table base */
    z80_ld_mem_hl_label(&enc, "free_table_list");   /* free_table_list = HL */
    z80_ret(&enc);

    /* Mark byte is stored in table header byte 1.
     * Header layout: [0]=entry_count, [1]=gc_mark, [2]=capacity, [3]=reserved */
    z80_add_label(&enc, "mark_table_reachable");  /* HL = table ptr */
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_reachable_nonzero");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_reachable_done");
    z80_add_label(&enc, "mark_table_reachable_nonzero");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_reachable_done");
    z80_ld_r_n(&enc, REG_A, 1);
    z80_ld_hl_a(&enc);
    z80_ld_hl_mem_label(&enc, "gc_mark_table_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "gc_mark_table_count");
    z80_add_label(&enc, "mark_table_reachable_done");
    z80_ret(&enc);

    z80_add_label(&enc, "mark_table_roots_globals");
    z80_ld_rp_label(&enc, RP_HL, "global_vars");
    z80_ld_r_n(&enc, REG_B, 0); /* 256 slots */
    z80_add_label(&enc, "mark_table_roots_globals_loop");
    z80_push(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, TYPE_TABLE);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_roots_globals_next");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_push(&enc, RP_BC);
    z80_call_label(&enc, "mark_table_reachable");
    z80_pop(&enc, RP_BC);
    z80_add_label(&enc, "mark_table_roots_globals_next");
    z80_pop(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_djnz_label(&enc, "mark_table_roots_globals_loop");
    z80_ret(&enc);

    z80_add_label(&enc, "mark_table_roots_vstack");
    z80_ld_hl_mem_label(&enc, "vsp_ptr");
    z80_add_label(&enc, "mark_table_roots_vstack_loop");
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_DE, "vstack_end");
    z80_or_a(&enc);
    z80_sbc_hl_rp(&enc, RP_DE);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_roots_vstack_done");
    z80_pop(&enc, RP_HL);

    z80_push(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, TYPE_TABLE);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_roots_vstack_next");
    z80_dec_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_dec_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_call_label(&enc, "mark_table_reachable");
    z80_add_label(&enc, "mark_table_roots_vstack_next");
    z80_pop(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_jr_label(&enc, "mark_table_roots_vstack_loop");

    z80_add_label(&enc, "mark_table_roots_vstack_done");
    z80_pop(&enc, RP_HL);
    z80_ret(&enc);

    z80_add_label(&enc, "mark_table_roots_frame");
    z80_ld_hl_mem_label(&enc, "fp_ptr");
    z80_ld_de_mem_label(&enc, "vsp_ptr");
    z80_add_label(&enc, "mark_table_roots_frame_loop");
    z80_push(&enc, RP_HL);
    z80_or_a(&enc);
    z80_sbc_hl_rp(&enc, RP_DE);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_roots_frame_done");
    z80_pop(&enc, RP_HL);

    z80_push(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, TYPE_TABLE);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_roots_frame_next");
    z80_dec_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_dec_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_call_label(&enc, "mark_table_reachable");
    z80_add_label(&enc, "mark_table_roots_frame_next");
    z80_pop(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_jr_label(&enc, "mark_table_roots_frame_loop");

    z80_add_label(&enc, "mark_table_roots_frame_done");
    z80_pop(&enc, RP_HL);
    z80_ret(&enc);

    z80_add_label(&enc, "mark_table_roots");
    z80_call_label(&enc, "mark_table_roots_globals");
    z80_call_label(&enc, "mark_table_roots_vstack");
    z80_call_label(&enc, "mark_table_roots_frame");
    z80_call_label(&enc, "mark_table_roots_current_env");
    z80_call_label(&enc, "mark_table_roots_current_closure");
    z80_ret(&enc);

    z80_add_label(&enc, "mark_table_cell"); /* HL = cell ptr [value_lo][value_hi][type] */
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_cp_a_n(&enc, TYPE_TABLE);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_cell_done");
    z80_ex_de_hl(&enc);
    z80_call_label(&enc, "mark_table_reachable");
    z80_add_label(&enc, "mark_table_cell_done");
    z80_ret(&enc);

    z80_add_label(&enc, "mark_table_roots_current_env");
    z80_ld_de_mem_label(&enc, "current_env_ptr");
    z80_ld_r_r(&enc, REG_A, REG_D);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_roots_current_env_has_env");
    z80_ld_r_r(&enc, REG_A, REG_E);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_roots_current_env_done");
    z80_add_label(&enc, "mark_table_roots_current_env_has_env");

    z80_ld_hl_mem_label(&enc, "current_closure_ptr");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_roots_current_env_has_closure");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_roots_current_env_done");
    z80_add_label(&enc, "mark_table_roots_current_env_has_closure");

    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);     /* env local count */
    z80_ld_r_r(&enc, REG_B, REG_A);
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_roots_current_env_done");
    z80_ld_r_r(&enc, REG_H, REG_D);
    z80_ld_r_r(&enc, REG_L, REG_E);

    z80_add_label(&enc, "mark_table_roots_current_env_loop");
    z80_push(&enc, RP_BC);
    z80_call_label(&enc, "mark_table_cell");
    z80_pop(&enc, RP_BC);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_djnz_label(&enc, "mark_table_roots_current_env_loop");
    z80_add_label(&enc, "mark_table_roots_current_env_done");
    z80_ret(&enc);

    z80_add_label(&enc, "mark_table_roots_current_closure");
    z80_ld_hl_mem_label(&enc, "current_closure_ptr");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "mark_table_roots_current_closure_nonzero");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_roots_current_closure_done");
    z80_add_label(&enc, "mark_table_roots_current_closure_nonzero");

    z80_push(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);   /* upvalue count */
    z80_ld_r_r(&enc, REG_B, REG_A);
    z80_pop(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "mark_table_roots_current_closure_done");

    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL); /* HL = first captured cell pointer entry */

    z80_add_label(&enc, "mark_table_roots_current_closure_loop");
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_push(&enc, RP_BC);
    z80_ld_r_r(&enc, REG_H, REG_D);
    z80_ld_r_r(&enc, REG_L, REG_E);
    z80_call_label(&enc, "mark_table_cell");
    z80_pop(&enc, RP_BC);
    z80_pop(&enc, RP_HL);
    z80_djnz_label(&enc, "mark_table_roots_current_closure_loop");
    z80_add_label(&enc, "mark_table_roots_current_closure_done");
    z80_ret(&enc);

    z80_add_label(&enc, "table_is_marked_clear"); /* HL = table ptr, A=1 if marked else 0 */
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "table_is_marked_clear_nonzero");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "table_is_marked_clear_unmarked");
    z80_add_label(&enc, "table_is_marked_clear_nonzero");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "table_is_marked_clear_unmarked");
    z80_xor_a(&enc);
    z80_ld_hl_a(&enc);
    z80_ld_r_n(&enc, REG_A, 1);
    z80_ret(&enc);
    z80_add_label(&enc, "table_is_marked_clear_unmarked");
    z80_xor_a(&enc);
    z80_ret(&enc);

    /* Queue a table pointer for deferred reclaim. This is non-intrusive:
     * the table object is not modified until a future mark phase proves it
     * unreachable and calls gc_sweep_deferred_tables. Input: HL=table ptr. */
    z80_add_label(&enc, "queue_table_reclaim_candidate");
    z80_ld_mem_hl_label(&enc, "table_reclaim_candidate");
    z80_ld_rp_label(&enc, RP_HL, "pending_table_reclaim_tail");
    z80_ld_a_hl(&enc);
    z80_ld_r_r(&enc, REG_C, REG_A);
    z80_inc_r(&enc, REG_A);
    z80_cp_a_n(&enc, TABLE_RECLAIM_QUEUE_CAP);
    z80_jr_cc_label(&enc, CC_NZ, "queue_table_reclaim_no_wrap");
    z80_xor_a(&enc);
    z80_add_label(&enc, "queue_table_reclaim_no_wrap");
    z80_ld_r_r(&enc, REG_B, REG_A);
    z80_ld_rp_label(&enc, RP_HL, "pending_table_reclaim_head");
    z80_ld_a_hl(&enc);
    z80_cp_a_r(&enc, REG_B);
    z80_jr_cc_label(&enc, CC_Z, "queue_table_reclaim_full");

    z80_ld_r_r(&enc, REG_L, REG_C);
    z80_ld_r_n(&enc, REG_H, 0);
    z80_add_hl_rp(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_DE, "pending_table_reclaim_buf");
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_de_mem_label(&enc, "table_reclaim_candidate");
    z80_ld_r_r(&enc, REG_M, REG_E);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_M, REG_D);
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_ld_rp_label(&enc, RP_HL, "pending_table_reclaim_tail");
    z80_ld_hl_a(&enc);
    z80_ret(&enc);

    z80_add_label(&enc, "queue_table_reclaim_full");
    z80_ld_hl_mem_label(&enc, "pending_table_reclaim_dropcnt");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "pending_table_reclaim_dropcnt");
    z80_ret(&enc);

    /* Sweep deferred table candidates after a mark phase has identified
     * unreachable objects. For now this blindly reclaims queued entries and
     * is intended to be called only by future mark/sweep plumbing. */
    z80_add_label(&enc, "gc_sweep_deferred_tables");
    z80_ld_rp_label(&enc, RP_HL, "gc_sweep_enabled");
    z80_ld_a_hl(&enc);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "gc_sweep_deferred_tables_done");
    z80_call_label(&enc, "mark_table_roots");

    z80_ld_rp_label(&enc, RP_HL, "pending_table_reclaim_head");
    z80_ld_a_hl(&enc);
    z80_ld_r_r(&enc, REG_C, REG_A);
    z80_ld_rp_label(&enc, RP_HL, "pending_table_reclaim_tail");
    z80_ld_a_hl(&enc);
    z80_cp_a_r(&enc, REG_C);
    z80_jr_cc_label(&enc, CC_Z, "gc_sweep_deferred_tables_done");

    z80_ld_r_r(&enc, REG_A, REG_C);
    z80_inc_r(&enc, REG_A);
    z80_cp_a_n(&enc, TABLE_RECLAIM_QUEUE_CAP);
    z80_jr_cc_label(&enc, CC_NZ, "gc_sweep_deferred_tables_next_ready");
    z80_xor_a(&enc);
    z80_add_label(&enc, "gc_sweep_deferred_tables_next_ready");
    z80_ld_r_r(&enc, REG_B, REG_A);

    z80_ld_r_r(&enc, REG_L, REG_C);
    z80_ld_r_n(&enc, REG_H, 0);
    z80_add_hl_rp(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_DE, "pending_table_reclaim_buf");
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_ex_de_hl(&enc);
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "gc_sweep_deferred_tables_has_ptr");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_Z, "gc_sweep_deferred_tables_store_head");

    z80_add_label(&enc, "gc_sweep_deferred_tables_has_ptr");
    z80_push(&enc, RP_HL);
    z80_call_label(&enc, "table_is_marked_clear");
    z80_pop(&enc, RP_HL);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "gc_sweep_deferred_tables_store_head");
    z80_call_label(&enc, "free_table_object");
    z80_ld_hl_mem_label(&enc, "gc_sweep_table_count");
    z80_inc_rp(&enc, RP_HL);
    z80_ld_mem_hl_label(&enc, "gc_sweep_table_count");

    z80_add_label(&enc, "gc_sweep_deferred_tables_store_head");
    z80_ld_r_r(&enc, REG_A, REG_B);
    z80_ld_rp_label(&enc, RP_HL, "pending_table_reclaim_head");
    z80_ld_hl_a(&enc);
    z80_jr_label(&enc, "gc_sweep_deferred_tables");

    z80_add_label(&enc, "gc_sweep_deferred_tables_done");
    z80_ret(&enc);

    z80_add_label(&enc, "op_newtable");
    z80_call_label(&enc, "alloc_table_object");
    z80_ld_r_r(&enc, REG_A, REG_H);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "newtable_alloc_ok");
    z80_ld_r_r(&enc, REG_A, REG_L);
    z80_or_a(&enc);
    z80_jr_cc_label(&enc, CC_NZ, "newtable_alloc_ok");
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "newtable_alloc_ok");
    z80_push(&enc, RP_HL);
    z80_ld_r_n(&enc, REG_B, TABLE_SIZE);
    z80_xor_a(&enc);
    z80_add_label(&enc, "newtable_clear_loop");
    z80_ld_hl_a(&enc);
    z80_inc_rp(&enc, RP_HL);
    z80_djnz_label(&enc, "newtable_clear_loop");
    z80_pop(&enc, RP_HL);

    z80_push(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_n(&enc, REG_A, TABLE_CAPACITY);
    z80_ld_hl_a(&enc);
    z80_pop(&enc, RP_HL);
    z80_ld_r_n(&enc, REG_A, TYPE_TABLE);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_gettable");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "table_key_temp");
    z80_ld_rp_label(&enc, RP_HL, "table_key_type");
    z80_ld_hl_a(&enc);
    z80_call_label(&enc, "vstack_pop");
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_A, REG_B); z80_or_a(&enc);
    z80_jp_cc_label(&enc, CC_Z, "get_table_not_found");
    z80_add_label(&enc, "get_table_loop");
    z80_push(&enc, RP_HL); z80_push(&enc, RP_BC);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_ld_rp_label(&enc, RP_HL, "table_key_type");
    z80_ld_a_hl(&enc);
    z80_cp_a_r(&enc, REG_C);
    z80_jp_cc_label(&enc, CC_NZ, "get_table_next");
    z80_cp_a_n(&enc, TYPE_STRING);
    z80_jp_cc_label(&enc, CC_Z, "get_table_string_compare");
    z80_ld_hl_mem_label(&enc, "table_key_temp");
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_jp_cc_label(&enc, CC_NZ, "get_table_next");
    z80_jp_label(&enc, "get_table_match");
    z80_add_label(&enc, "get_table_string_compare");
    z80_ld_hl_mem_label(&enc, "table_key_temp");
    z80_call_label(&enc, "strcmp_hl_de");
    z80_jp_cc_label(&enc, CC_NZ, "get_table_next");
    z80_add_label(&enc, "get_table_match");
    z80_pop(&enc, RP_BC);
    z80_pop(&enc, RP_HL);
    z80_ld_rp_nn(&enc, RP_DE, 3);
    z80_add_hl_rp(&enc, RP_DE);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_a_hl(&enc);
    z80_ex_de_hl(&enc);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");
    z80_add_label(&enc, "get_table_next");
    z80_pop(&enc, RP_BC);
    z80_pop(&enc, RP_HL);
    z80_ld_rp_nn(&enc, RP_DE, TABLE_ENTRY_SIZE);
    z80_add_hl_rp(&enc, RP_DE);
    z80_djnz_label(&enc, "get_table_loop");
    z80_add_label(&enc, "get_table_not_found");
    z80_ld_rp_nn(&enc, RP_HL, 0);
    z80_ld_r_n(&enc, REG_A, TYPE_NIL);
    z80_call_label(&enc, "vstack_push");
    z80_jp_label(&enc, "vm_loop");

    z80_add_label(&enc, "op_settable");
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "table_val_temp");
    z80_ld_rp_label(&enc, RP_HL, "table_val_type");
    z80_ld_hl_a(&enc);
    z80_call_label(&enc, "vstack_pop");
    z80_ld_mem_hl_label(&enc, "table_key_temp");
    z80_ld_rp_label(&enc, RP_HL, "table_key_type");
    z80_ld_hl_a(&enc);
    z80_call_label(&enc, "vstack_pop");
    z80_push(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_B, REG_M);
    z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL); z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_A, REG_B); z80_or_a(&enc);
    z80_jp_cc_label(&enc, CC_Z, "set_table_new_entry");
    z80_add_label(&enc, "set_table_loop");
    z80_push(&enc, RP_HL); z80_push(&enc, RP_BC);
    z80_ld_r_r(&enc, REG_E, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_D, REG_M);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_C, REG_M);
    z80_ld_rp_label(&enc, RP_HL, "table_key_type");
    z80_ld_a_hl(&enc);
    z80_cp_a_r(&enc, REG_C);
    z80_jp_cc_label(&enc, CC_NZ, "set_table_next");
    z80_cp_a_n(&enc, TYPE_STRING);
    z80_jp_cc_label(&enc, CC_Z, "set_table_string_compare");
    z80_ld_hl_mem_label(&enc, "table_key_temp");
    z80_or_a(&enc); z80_emit_b(&enc, 0xED); z80_emit_b(&enc, 0x52);
    z80_jp_cc_label(&enc, CC_NZ, "set_table_next");
    z80_jp_label(&enc, "set_table_match");
    z80_add_label(&enc, "set_table_string_compare");
    z80_ld_hl_mem_label(&enc, "table_key_temp");
    z80_call_label(&enc, "strcmp_hl_de");
    z80_jp_cc_label(&enc, CC_NZ, "set_table_next");
    z80_add_label(&enc, "set_table_match");
    z80_pop(&enc, RP_BC);
    z80_pop(&enc, RP_HL);
    z80_pop(&enc, RP_BC);
    z80_ld_rp_nn(&enc, RP_DE, 3);
    z80_add_hl_rp(&enc, RP_DE);
    z80_jp_label(&enc, "set_table_write_value");
    z80_add_label(&enc, "set_table_next");
    z80_pop(&enc, RP_BC);
    z80_pop(&enc, RP_HL);
    z80_ld_rp_nn(&enc, RP_DE, TABLE_ENTRY_SIZE);
    z80_add_hl_rp(&enc, RP_DE);
    z80_djnz_label(&enc, "set_table_loop");
    z80_add_label(&enc, "set_table_new_entry");
    z80_ld_mem_hl_label(&enc, "table_entry_temp");
    z80_pop(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_A, REG_M);
    z80_cp_a_n(&enc, TABLE_CAPACITY);
    z80_jp_cc_label(&enc, CC_NC, "set_table_full");
    z80_inc_r(&enc, REG_M);
    z80_ld_hl_mem_label(&enc, "table_entry_temp");
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "table_key_temp");
    z80_ex_de_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_M, REG_E);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_M, REG_D);
    z80_inc_rp(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_HL, "table_key_type");
    z80_ld_a_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_ld_hl_a(&enc);
    z80_inc_rp(&enc, RP_HL);
    z80_jp_label(&enc, "set_table_write_value");
    z80_add_label(&enc, "set_table_full");
    z80_jp_label(&enc, "vm_loop");
    z80_add_label(&enc, "set_table_write_value");
    z80_push(&enc, RP_HL);
    z80_ld_hl_mem_label(&enc, "table_val_temp");
    z80_ex_de_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_M, REG_E);
    z80_inc_rp(&enc, RP_HL);
    z80_ld_r_r(&enc, REG_M, REG_D);
    z80_inc_rp(&enc, RP_HL);
    z80_push(&enc, RP_HL);
    z80_ld_rp_label(&enc, RP_HL, "table_val_type");
    z80_ld_a_hl(&enc);
    z80_pop(&enc, RP_HL);
    z80_ld_hl_a(&enc);
    z80_jp_label(&enc, "vm_loop");
}

void emit_io_and_arithmetic_ops(void) {
    emit_stack_and_closure_ops();
    emit_print_and_string_ops();
    emit_numeric_and_misc_ops();
    emit_table_ops();
}